// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Av57eKG5mVK-lCll69Vfglai-8Bo6F8',
    appId: '1:780551536550:web:61f2374f8a8d76003c5967',
    messagingSenderId: '780551536550',
    projectId: 'parmigiano-menu',
    authDomain: 'parmigiano-menu.firebaseapp.com',
    storageBucket: 'parmigiano-menu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4EqdwVv32-KJVPhI_YvOgYQnbhZzP8aM',
    appId: '1:780551536550:android:58650bb73c7803a63c5967',
    messagingSenderId: '780551536550',
    projectId: 'parmigiano-menu',
    storageBucket: 'parmigiano-menu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjomjCNBmudJINJWh3QHoroom9Z_rUwFI',
    appId: '1:780551536550:ios:682b4b05304cf1f23c5967',
    messagingSenderId: '780551536550',
    projectId: 'parmigiano-menu',
    storageBucket: 'parmigiano-menu.firebasestorage.app',
    iosBundleId: 'no',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjomjCNBmudJINJWh3QHoroom9Z_rUwFI',
    appId: '1:780551536550:ios:125902ae23d64e0a3c5967',
    messagingSenderId: '780551536550',
    projectId: 'parmigiano-menu',
    storageBucket: 'parmigiano-menu.firebasestorage.app',
    iosBundleId: 'com.example.parmigianoMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Av57eKG5mVK-lCll69Vfglai-8Bo6F8',
    appId: '1:780551536550:web:35352a808002884a3c5967',
    messagingSenderId: '780551536550',
    projectId: 'parmigiano-menu',
    authDomain: 'parmigiano-menu.firebaseapp.com',
    storageBucket: 'parmigiano-menu.firebasestorage.app',
  );
}
